server-name: idp.localhost.com:9443
listen-address: ":9443"
tls-ca: ""
tls-certificate: C:/lite-idp/keys/servercert.pem
tls-private-key: C:/lite-idp/keys/serverkey.pem

sps:
- entityid: tecan.config.management
  assertionconsumerservices:
  - index: 0
    isdefault: true
    binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
    location: http://localhost:8080/saml/SSO
  - index: 1
    isdefault: false
    binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact
    location: http://localhost:8080/saml/SSO
  singleLogoutServices:
  - index: 0
    isdefault: true
    binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
    location: http://localhost:8080/saml/SingleLogout
  certificate: |-
    MIIDUjCCAjqgAwIBAgIEUOLIQTANBgkqhkiG9w0BAQUFADBrMQswCQYDVQQGEwJGSTEQMA4GA1UE
    CBMHVXVzaW1hYTERMA8GA1UEBxMISGVsc2lua2kxGDAWBgNVBAoTD1JNNSBTb2Z0d2FyZSBPeTEM
    MAoGA1UECwwDUiZEMQ8wDQYDVQQDEwZhcG9sbG8wHhcNMTMwMTAxMTEyODAxWhcNMjIxMjMwMTEy
    ODAxWjBrMQswCQYDVQQGEwJGSTEQMA4GA1UECBMHVXVzaW1hYTERMA8GA1UEBxMISGVsc2lua2kx
    GDAWBgNVBAoTD1JNNSBTb2Z0d2FyZSBPeTEMMAoGA1UECwwDUiZEMQ8wDQYDVQQDEwZhcG9sbG8w
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCXqP0wqL2Ai1haeTj0alwsLafhrDtUt00E
    5xc7kdD7PISRA270ZmpYMB4W24Uk2QkuwaBp6dI/yRdUvPfOT45YZrqIxMe2451PAQWtEKWF5Z13
    F0J4/lB71TtrzyH94RnqSHXFfvRN8EY/rzuEzrpZrHdtNs9LRyLqcRTXMMO4z7QghBuxh3K5gu7K
    qxpHx6No83WNZj4B3gvWLRWv05nbXh/F9YMeQClTX1iBNAhLQxWhwXMKB4u1iPQ/KSaal3R26pON
    UUmu1qVtU1quQozSTPD8HvsDqGG19v2+/N3uf5dRYtvEPfwXN3wIY+/R93vBA6lnl5nTctZIRsyg
    0Gv5AgMBAAEwDQYJKoZIhvcNAQEFBQADggEBAFQwAAYUjso1VwjDc2kypK/RRcB8bMAUUIG0hLGL
    82IvnKouGixGqAcULwQKIvTs6uGmlgbSG6Gn5ROb2mlBztXqQ49zRvi5qWNRttir6eyqwRFGOM6A
    8rxj3Jhxi2Vb/MJn7XzeVHHLzA1sV5hwl/2PLnaL2h9WyG9QwBbwtmkMEqUt/dgixKb1Rvby/tBu
    RogWgPONNSACiW+Z5o8UdAOqNMZQozD/i1gOjBXoF0F5OksjQN7xoQZLj9xXefxCFQ69FPcFDeEW
    bHwSoBy5hLPNALaEUoa5zPDwlixwRjFQTc5XXaRpgIjy/2gsL8+Y5QRhyXnLqgO67BlLYW/GuHE=

users:
- attributes:
    GivenName:
    - Test
    SurName:
    - User
    Roles:
    - ROLE_QUERY_USER
    - ROLE_DATA_MANAGER
    - ROLE_FIELD_ENGINEER
  name: testuser@tecan.com
  password: $2a$10$e.gqggHWjBRt0ZZgliU6oe/gefiYbcd2cTUFJZ/Rxe1Fl3RUhnx8u